  
name: Publish if new versions in package.json
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: '10.x'
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/package1
          yarn
          yarn add semver
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
          chmod 0600 ~/.npmrc
          packages=$(curl \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: bearer ${GITHUB_TOKEN}" \
            --data '{ "query": "{ user(login: \"MMLudo\") { repository(name: \"actions_tests\") { packages(names: \"package1\" first:1) { edges { node { name latestVersion {version} } } } } } }" }' \
            https://api.github.com/graphql)
          currentVersion=$(echo "$packages" | jq -r .data.user.repository.packages.edges[0].node.latestVersion.version)
          pushedVersion=$(cat $GITHUB_WORKSPACE/package1/package.json | jq -r .version)
          newerVersion=$($GITHUB_WORKSPACE/package1/node_modules/semver/bin/semver.js $pushedVersion -r ">=$currentVersion")
          if [[ $newerVersion == $pushedVersion ]]; then yarn publish $GITHUB_WORKSPACE/package1; fi